import { getPlatformOverview } from "@/lib/platform-reporting";
import { PlatformShell,ReportFilters,ReportPeriod,Metrics,ActivityChart,Definitions } from "@/components/platform/report-ui";
import { decimal,reportOptions } from "@/lib/platform-report-options";
export const dynamic="force-dynamic";
export default async function AnalyticsPage({searchParams}:PageProps<"/platform/analytics">) {
  const search=await searchParams,data=await getPlatformOverview(search);
  return <PlatformShell title="Adoption and usage analytics"><ReportFilters search={search}/><ReportPeriod period={data}/>
    <Metrics items={[["Registered restaurant tenants",data.total_restaurants],["New registrations",data.new_restaurants],["First activations in period",data.first_activations],["Ever activated / current tenants",`${data.activated_restaurants} / ${data.total_restaurants}`],["Lifetime activation rate",data.activation_rate===null?"Unavailable (no tenants)":`${decimal(data.activation_rate)}%`],["Mean signup → first order (hours)",decimal(data.average_activation_hours)],["Active restaurants in period",data.active_restaurants],["Repeat-active restaurants",data.repeat_active],["Restaurants with no activity in period",data.inactive_restaurants],["Submitted orders (including cancelled)",data.orders],["Non-cancelled orders per active restaurant",decimal(data.average_orders_per_active)],["New signup cohort activated so far",`${data.new_cohort_activated} / ${data.new_restaurants}`],["Configured tables",data.tables],["Configured menu items",data.menu_items],["Configured operational staff accounts",data.staff_accounts]]}/>
    <p className="text-sm">Lifetime activation denominator: all currently existing tenants; numerator: tenants with at least one non-cancelled order before this report. New-cohort activation uses only tenants registered within the selected window. Repeat-active means activity both in the selected window and the preceding {reportOptions(search).days} calendar-day window. Today is partial. {data.invalid_activation_timestamps} signup/first-order timestamp anomalies excluded from mean activation time.</p>
    <div className="grid gap-4 lg:grid-cols-2"><ActivityChart rows={data.trend} metric="total_restaurants" title="Registered tenants over time (existing records)"/><ActivityChart rows={data.trend} metric="signups" title="New registrations per day"/><ActivityChart rows={data.trend} metric="active_restaurants" title="Distinct active restaurants per day"/><ActivityChart rows={data.trend} metric="orders" title="Submitted order volume"/></div>
    <p className="text-sm">Configuration counts include inactive rows. Operational staff excludes Owner/Manager accounts. Daily active counts must not be summed to obtain period-distinct activity. No SaaS financial metric is inferred from restaurant sales.</p><Definitions/>
  </PlatformShell>;
}
